# FlowSync AI - Environment Setup Wizard
# This script helps you set up your .env.local file with API keys

Write-Host "🔧 FlowSync AI - Environment Setup Wizard" -ForegroundColor Cyan
Write-Host "================================================" -ForegroundColor Cyan
Write-Host ""

# Function to securely get input
function Get-SecureInput {
    param([string]$prompt)
    Write-Host $prompt -ForegroundColor Yellow -NoNewline
    return Read-Host
}

# Create .env.local file
$envFile = ".env.local"

# Check if file exists
if (Test-Path $envFile) {
    Write-Host "✓ Found existing .env.local" -ForegroundColor Green
    $overwrite = Read-Host "Do you want to update it? (yes/no)"
    if ($overwrite -ne "yes") {
        Write-Host "Skipping setup..." -ForegroundColor Yellow
        exit
    }
}

Write-Host ""
Write-Host "📋 Let's set up your environment variables" -ForegroundColor Cyan
Write-Host ""

# Get Google API Key
Write-Host "Step 1: Google AI Studio API" -ForegroundColor Cyan
Write-Host "Get your key from: https://aistudio.google.com/app/apikey" -ForegroundColor Gray
$googleKey = Get-SecureInput "Enter your REACT_APP_GOOGLE_API_KEY: "

# Get Stripe Keys
Write-Host ""
Write-Host "Step 2: Stripe Payment Keys" -ForegroundColor Cyan
Write-Host "Get your keys from: https://dashboard.stripe.com/apikeys" -ForegroundColor Gray
$stripePublic = Get-SecureInput "Enter your REACT_APP_STRIPE_PUBLIC_KEY (pk_live_...): "
$stripeSecret = Get-SecureInput "Enter your STRIPE_SECRET_KEY (sk_live_...): "
$webhookSecret = Get-SecureInput "Enter your STRIPE_WEBHOOK_SECRET (whsec_...): "

# Build .env.local content
$envContent = @"
# Auto-generated by SETUP-ENV.ps1 on $(Get-Date)
# Google AI Studio Configuration
REACT_APP_GOOGLE_API_KEY=$googleKey
REACT_APP_GOOGLE_MODEL_NAME=gemini-1.5-pro

# Stripe Configuration
REACT_APP_STRIPE_PUBLIC_KEY=$stripePublic
STRIPE_SECRET_KEY=$stripeSecret
STRIPE_WEBHOOK_SECRET=$webhookSecret

# Application Configuration
REACT_APP_API_URL=https://wernerai.se
REACT_APP_ENVIRONMENT=production
REACT_APP_LOG_LEVEL=info

# Feature Flags
REACT_APP_ENABLE_REFERRAL_PROGRAM=true
REACT_APP_ENABLE_A_B_TESTING=true
"@

# Write to file
try {
    $envContent | Out-File -FilePath $envFile -Encoding UTF8
    Write-Host ""
    Write-Host "✅ SUCCESS!" -ForegroundColor Green
    Write-Host "============================================" -ForegroundColor Green
    Write-Host ".env.local has been created with your API keys" -ForegroundColor Green
    Write-Host "============================================" -ForegroundColor Green
    Write-Host ""
    Write-Host "Next steps:" -ForegroundColor Yellow
    Write-Host "1. Deploy to Vercel: https://vercel.com/import" -ForegroundColor Cyan
    Write-Host "2. Add environment variables in Vercel dashboard" -ForegroundColor Cyan
    Write-Host "3. Connect your domain (wernerai.se)" -ForegroundColor Cyan
}
catch {
    Write-Host "❌ Error creating .env.local: $_" -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "Press any key to continue..." -ForegroundColor White
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
